language: "en"
early_access: true
reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_instructions:
    - path: "src/app/**/*"
      instructions: |
        "Ensure the following for Next.js App Router:
        - Use server components by default unless client-side interactivity is required.
        - Proper use of loading.tsx, error.tsx, and layout.tsx for handling loading states, errors, and layouts.
        - Implement efficient data fetching with fetch(), getServerSession(), or direct database access in server components.
        - Ensure dynamic routes and parallel routes follow Next.js best practices."

    - path: "src/components/**/*"
      instructions: |
        "Verify that components:
        - Follow the React Server Components (RSC) paradigm when possible.
        - Are optimized for performance, avoiding unnecessary client-side state.
        - Use 'use client' only when required for interactivity.
        - Implement reusable UI patterns and modular component structures."

    - path: "src/lib/**/*"
      instructions: |
        "Check that:
        - Utility functions are optimized and well-organized.
        - API calls and database queries follow best practices.
        - Server-side utilities are properly used within the App Router architecture."

    - path: "src/styles/**/*"
      instructions: |
        "Ensure that styling:
        - Uses Tailwind CSS or other project-approved styling approaches.
        - Follows Next.js-specific best practices, such as avoiding global styles unless necessary.
        - Maintains a consistent design language across components."

    - path: "src/middleware.ts"
      instructions: |
        "Ensure that middleware:
        - Properly handles authentication, redirects, or headers when required.
        - Uses `NextResponse` effectively for rewriting, redirecting, or modifying responses.
        - Avoids unnecessary performance bottlenecks."

    - path: "src/app/api/**/*"
      instructions: |
        "Verify API route implementations:
        - Ensure proper use of Route Handlers (`src/app/api/.../route.ts` pattern).
        - Use the correct HTTP methods (GET, POST, PUT, DELETE).
        - Follow best security practices, including request validation and authentication checks."
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
chat:
  auto_reply: true
